site_name:        PrivateModules.jl
repo_url:         https://github.com/MichaelHatherly/PrivateModules.jl
site_description: Make unexported symbols private.
site_author:      Michael Hatherly

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
  - Home: index.md
